version: '3.8'
services:
  backend:
    build: .
    ports:
      - "5500:5500"
    volumes:
      - ./logs:/app/logs # Маппинг логов
  frontend:
    image: node:14
    working_dir: /app
    volumes:
      - ./front:/app # Папка с FRONT (из репозитория FRONT)
    ports:
      - "3000:3000"
    command: "npm start"