version: '3.8'
services:
  backend:
    build: .
    ports:
      - "5500:5500"
    volumes:
      - ./logs:/app/logs # Маппинг логов
      - ./src/main/resources:/app/resources # Добавляем монтирование resources
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  frontend:
    build:
      context: C:\Java\Project1\WEB\card-transfer
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:5500
    depends_on:
      - backend
